default:
  image: node:20.20.2@sha256:a4545fc6f4f1483384ad5f4c71d34d71781c3779da407173ec6058079a718520
  tags:
    - pangea-internal

stages:
  - build
  - lint
  - integration_tests
  - publish
  - tag_release
  - examples

include:
  - /examples/.gitlab-ci.yml
  - /packages/pangea-node-sdk/.gitlab-ci.yml
  - /packages/react-auth/.gitlab-ci.yml
  - /packages/react-mui-audit-log-viewer/.gitlab-ci.yml
  - /packages/react-mui-authn/.gitlab-ci.yml
  - /packages/react-mui-branding/.gitlab-ci.yml
  - /packages/react-mui-shared/.gitlab-ci.yml
  - /packages/react-mui-share-file-viewer/.gitlab-ci.yml
  - /packages/vanilla-js/.gitlab-ci.yml
  - /packages/webcomponents/.gitlab-ci.yml
