default:
  image: node:20.20.1@sha256:e391c5561646193be929e3fe55d27234f40a01d867d72b30ae1341b673a3bf4b
  tags:
    - pangea-internal

stages:
  - build
  - lint
  - integration_tests
  - publish
  - tag_release
  - examples

include:
  - /examples/.gitlab-ci.yml
  - /packages/pangea-node-sdk/.gitlab-ci.yml
  - /packages/react-auth/.gitlab-ci.yml
  - /packages/react-mui-audit-log-viewer/.gitlab-ci.yml
  - /packages/react-mui-authn/.gitlab-ci.yml
  - /packages/react-mui-branding/.gitlab-ci.yml
  - /packages/react-mui-shared/.gitlab-ci.yml
  - /packages/react-mui-share-file-viewer/.gitlab-ci.yml
  - /packages/vanilla-js/.gitlab-ci.yml
  - /packages/webcomponents/.gitlab-ci.yml
