.react_mui_branding_base:
  image: node:20.19.4@sha256:a6c4ae2f61d3807514fc4b152b5b37810c70e836303d361d9f84d3842534d666
  before_script:
    - cd packages/react-mui-branding
    - yarn install --frozen-lockfile
    - apt-get -qq update
    - apt-get install -y jq
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - node_modules

publish_react_mui_branding:
  extends: .react_mui_branding_base
  stage: publish
  script:
    - cp ../../scripts/publish.sh .
    - echo "${NPMRC}" > .npmrc && ./publish.sh && rm .npmrc
    - rm publish.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - packages/react-mui-branding/**/*
      when: on_success
