export const PANGEA: any = {
  authn_show_name: "yes",
  bg_color: "#F6F9FC",
  bg_image: "",
  body_font_size: "14px",
  body_font_weight: "400",
  brand_favicon:
    "https://pangea-marketing.s3.us-west-2.amazonaws.com/favicon.ico",
  brand_logo:
    "https://pangea-marketing.s3.us-west-2.amazonaws.com/pangea-color.png",
  brand_logo_height: "24px",
  brand_name: "Pangea",
  brand_page_logo:
    "https://pangea-marketing.s3.us-west-2.amazonaws.com/pangea-color-beta.svg",
  brand_url: "",
  button_border_radius: "4px",
  button_variant: "contained",
  density: "normal",
  font_family: "Kanit",
  header_font_size: "24px",
  header_font_weight: "600",
  id: "pro_ser3ddzl66t4hdxit7hazqimc674xzk5",
  input_bg_color: "#FFFFFF",
  input_border_color: "",
  input_border_radius: "4px",
  link_color: "#551B76",
  link_style: "none",
  login_button_label: "Sign in",
  login_heading: "Sign in",
  login_social_heading: "Other ways to sign in",
  name: "Tmp 1",
  otp_button_label: "Submit",
  otp_font_size: "42px",
  panel_bg_color: "#FFFFFF",
  panel_border_radius: "8px",
  panel_box_shadow: "0px 8px 24px rgba(0, 0, 0, 0.16)",
  primary_color: "#551B76",
  secondary_color: "#F1F4F7",
  signup_button_label: "Create account",
  signup_heading: "Create your account",
  signup_social_heading: "Other ways to sign up",
  social_icon_style: "",
  support_email: "",
  text_contrast_color: "#FFF",
  text_primary_color: "#23315A",
  text_secondary_color: "#727A92",
  updated_at: "2023-01-18T19:21:40.716282Z",
  custom_metadata: {
    audit: {
      column_header_bg_color: "#F1F4F7",
      selected_row_bg_color: "#F1F4F7",
      // hover_row_bg_color: "#d4dce5",
    },
  },
  eula_heading: "License Agreement",
  privacy_heading: "Privacy Policy",
};
