export const AIDR: any = {
  authn_show_name: "no",
  bg_color: "#F6F9FC",
  bg_image: "",
  body_font_size: "14px",
  body_font_weight: "400",
  brand_favicon:
    "https://pangea-marketing.s3.us-west-2.amazonaws.com/favicon.ico",
  brand_logo:
    "https://pangea-marketing.s3.us-west-2.amazonaws.com/pangea_aidir_logo.png",
  brand_logo_height: "80px",
  brand_name: "Pangea AIDR",
  brand_page_logo:
    "https://pangea-marketing.s3.us-west-2.amazonaws.com/pangea_aidir_logo.png",
  brand_url: "",
  button_border_radius: "100px",
  button_variant: "contained",
  density: "normal",
  spacing: "20",
  font_family: "Inter",
  header_font_size: "24px",
  header_font_weight: "600",
  input_bg_color: "#0A0C0C",
  input_border_color: "#FFFFFF",
  input_border_radius: "8px",
  link_color: "#FFFFFF7F",
  link_style: "none",
  login_button_label: "Sign in",
  login_heading: "Sign in",
  login_social_heading: "Other ways to sign in",
  otp_button_label: "Submit",
  otp_font_size: "42px",
  panel_bg_color: "#0A0C0C",
  panel_border_radius: "8px",
  panel_box_shadow: "none",
  primary_color: "#551B76",
  secondary_color: "#F6F9FC",
  primary_button_border: "1px solid #9D4CDE",
  secondary_button_border: "1px solid #FFFFFF33",
  signup_button_label: "Create account",
  signup_heading: "Create your account",
  signup_social_heading: "Other ways to sign up",
  social_icon_style: "",
  social_icon_only: true,
  support_email: "",
  text_contrast_color: "#FFF",
  text_primary_color: "#FFFFFF",
  text_secondary_color: "#FFFFFF",
  start_heading: "Log in",
  eula_heading: "License Agreement",
  privacy_heading: "Privacy Policy",
};
