export const GENERIC: any = {
  authn_cancel_label: "Start over",
  authn_show_name: "yes",
  authn_show_social_icons: true,
  authn_submit_label: "Submit",
  bg_color: "#f0f0f0",
  bg_image: "",
  body_font_size: "14px",
  body_font_weight: "400",
  brand_favicon: "",
  brand_logo: "",
  brand_logo_height: "24px",
  brand_name: "Your brand name",
  brand_page_logo: "",
  brand_url: "",
  button_border_radius: "4px",
  button_variant: "contained",
  captcha_heading: "Prove you're human",
  density: "normal",
  eula_heading: "License Agreement",
  font_family: "Roboto",
  header_font_size: "24px",
  header_font_weight: "600",
  id: "pro_qasx5ts6fhayj5kmt4rvgyceze2x66hj",
  input_bg_color: "#FFFFFF",
  input_border_color: "#14FF00",
  input_border_radius: "4px",
  input_text_color: "",
  link_color: "#0070ff",
  link_style: "none",
  otp_button_label: "Submit",
  otp_font_size: "42px",
  panel_bg_color: "#FFFFFF",
  panel_border_radius: "8px",
  panel_box_shadow: "0px 8px 24px rgba(0, 0, 0, 0.16)",
  password_button_label: "Continue",
  password_heading: "Sign in",
  primary_color: "#000000",
  privacy_heading: "Privacy Policy",
  secondary_color: "#eeeeee",
  signup_button_label: "Continue",
  signup_heading: "Signup",
  social_heading: "Other ways",
  social_icon_style: "",
  start_button_label: "Continue with email",
  start_heading: "Log in or Sign up",
  support_email: "support@testdomain.com",
  text_contrast_color: "#FFF",
  text_primary_color: "#000000",
  text_secondary_color: "#999999",
};
