.examples-base:
  stage: Examples
  needs: [pack_pangea_node_sdk]
  parallel:
    matrix:
      - NODE_VERSION: [18, 20]
  image: node:${NODE_VERSION}
  before_script:
    - export PANGEA_AUDIT_CONFIG_ID="${PANGEA_AUDIT_CONFIG_ID_1_LVE}"
    - export PANGEA_AUDIT_CUSTOM_SCHEMA_TOKEN="${PANGEA_INTEGRATION_CUSTOM_SCHEMA_TOKEN_LVE}"
    - export PANGEA_AUDIT_MULTICONFIG_TOKEN="${PANGEA_INTEGRATION_MULTI_CONFIG_TOKEN_LVE}"
    - export PANGEA_AUDIT_TOKEN="${PANGEA_INTEGRATION_TOKEN_LVE}"
    - export PANGEA_AUTHN_TOKEN="${PANGEA_INTEGRATION_TOKEN_LVE}"
    - export PANGEA_DOMAIN_INTEL_TOKEN="${PANGEA_INTEGRATION_TOKEN_LVE}"
    - export PANGEA_DOMAIN="${PANGEA_INTEGRATION_DOMAIN_LVE}"
    - export PANGEA_EMBARGO_TOKEN="${PANGEA_INTEGRATION_TOKEN_LVE}"
    - export PANGEA_FILE_INTEL_TOKEN="${PANGEA_INTEGRATION_TOKEN_LVE}"
    - export PANGEA_FILE_SCAN_TOKEN="${PANGEA_INTEGRATION_TOKEN_LVE}"
    - export PANGEA_INTEL_TOKEN="${PANGEA_INTEGRATION_TOKEN_LVE}"
    - export PANGEA_IP_INTEL_TOKEN="${PANGEA_INTEGRATION_TOKEN_LVE}"
    - export PANGEA_REDACT_CONFIG_ID="${PANGEA_REDACT_CONFIG_ID_1_LVE}"
    - export PANGEA_REDACT_MULTICONFIG_TOKEN="${PANGEA_INTEGRATION_MULTI_CONFIG_TOKEN_LVE}"
    - export PANGEA_REDACT_TOKEN="${PANGEA_INTEGRATION_TOKEN_LVE}"
    - export PANGEA_URL_INTEL_TOKEN="${PANGEA_INTEGRATION_TOKEN_LVE}"
    - export PANGEA_USER_INTEL_TOKEN="${PANGEA_INTEGRATION_TOKEN_LVE}"
    - export PANGEA_VAULT_TOKEN="${PANGEA_INTEGRATION_TOKEN_LVE}"
    - pushd packages/pangea-node-sdk
    - tar -xf pangea-node-sdk-v*.tgz --strip-components 1 -C .
    - popd

examples-audit:
  extends: .examples-base
  script:
    - cd examples/audit
    - yarn install --frozen-lockfile --immutable
    - bash ../../dev/run_all_examples.sh

examples-authn:
  extends: .examples-base
  script:
    - cd examples/authn
    - yarn install --frozen-lockfile --immutable
    - bash ../../dev/run_all_examples.sh

examples-embargo:
  extends: .examples-base
  script:
    - cd examples/embargo
    - yarn install --frozen-lockfile --immutable
    - bash ../../dev/run_all_examples.sh

examples-file-scan:
  extends: .examples-base
  script:
    - cd examples/file_scan
    - yarn install --frozen-lockfile --immutable
    - bash ../../dev/run_all_examples.sh

examples-intel:
  extends: .examples-base
  script:
    - cd examples/intel
    - yarn install --frozen-lockfile --immutable
    - bash ../../dev/run_all_examples.sh

examples-redact:
  extends: .examples-base
  script:
    - cd examples/redact
    - yarn install --frozen-lockfile --immutable
    - bash ../../dev/run_all_examples.sh

examples-vault:
  extends: .examples-base
  script:
    - cd examples/vault
    - yarn install --frozen-lockfile --immutable
    - bash ../../dev/run_all_examples.sh
