.vanilla_js_base:
  image: node:20.20.2@sha256:a4545fc6f4f1483384ad5f4c71d34d71781c3779da407173ec6058079a718520
  before_script:
    - cd packages/vanilla-js
    - yarn install
    - apt-get -qq update
    - apt-get install -y jq

publish_vanilla_js:
  extends: .vanilla_js_base
  stage: publish
  script:
    - cp ../../scripts/publish.sh .
    - echo "${NPMRC}" > .npmrc && ./publish.sh && rm .npmrc
    - rm publish.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - packages/vanilla-js/**/*
      when: on_success
