.example_audit_log_viewer_base:
  image: cypress/browsers:node18.12.0-chrome103-ff107
  before_script:
    - cd examples/react-audit-log-viewer
    - yarn install --frozen-lockfile
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - node_modules
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - examples/react-audit-log-viewer/**/*
      when: on_success

.validate_example_audit_is_latest:
  extends: .example_audit_log_viewer_base
  stage: lint
  script:
    - cp ../../scripts/validate_latest_installed.sh .
    - ./validate_latest_installed.sh @pangeacyber/react-mui-audit-log-viewer
    - ./validate_latest_installed.sh @pangeacyber/react-mui-branding
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - packages/react-mui-audit-log-viewer/**/*
        - packages/react-mui-branding/**/*
      when: on_success

test_example_audit_app:
  extends: .example_audit_log_viewer_base
  stage: integration_tests
  script:
    - yarn cypress:ci
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - examples/react-audit-log-viewer/**/*
      when: on_success
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - examples/react-audit-log-viewer/**/*
      when: on_success
