.react_mui_audit_log_viewer_base:
  image: node:20.16.0@sha256:1ae9ba874435551280e95c8a8e74adf8a48d72b564bf9dfe4718231f2144c88f
  before_script:
    - cd packages/react-mui-audit-log-viewer
    - yarn install
    - apt-get -qq update
    - apt-get install -y jq
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - node_modules

publish_react_mui_audit_log_viewer:
  extends: .react_mui_audit_log_viewer_base
  stage: publish
  script:
    - cp ../../scripts/publish.sh .
    - echo "${NPMRC}" > .npmrc && ./publish.sh && rm .npmrc
    - rm publish.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - packages/react-mui-audit-log-viewer/**/*
      when: always
