import type { Metadata } from "next";

import { AuthProvider } from "@pangeacyber/nextjs-auth/client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <AuthProvider
      loginUrl={process.env.NEXT_PUBLIC_PANGEA_AUTHN_HOSTED_LOGIN_URL!}
      config={{
        clientToken: process.env.NEXT_PUBLIC_PANGEA_AUTHN_CLIENT_TOKEN!,
        domain: process.env.NEXT_PUBLIC_PANGEA_DOMAIN!,
      }}
    >
      <html lang="en">
        <body>{children}</body>
      </html>
    </AuthProvider>
  );
}
