export const BROWSERFLIX = {
  preset: "browserflix",

  brand_name: "Browserflix",
  brand_logo: "https://i.ibb.co/wB4VNcm/browserflix.png",
  brand_page_logo: "https://i.ibb.co/wB4VNcm/browserflix.png",
  brand_logo_height: "24px",
  brand_favicon: "",
  bg_image:
    "https://images.unsplash.com/photo-1574267432553-4b4628081c31?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2062&q=80",
  font_family: "Kanit",
  density: "comfortable",
  bg_color: "#4B4B4B",
  panel_bg_color: "rgba(0, 0, 0, 0.5)",
  primary_color: "#DF011A",
  secondary_color: "#4B4B4B",
  text_primary_color: "#FFFFFF",
  text_secondary_color: "#FFFFFF",
  text_contrast_color: "#FFFFFF",
  link_color: "#FFFFFF",
  input_text_color: "#FFFFFF",
  link_style: "none",
  header_font_size: "24px",
  header_font_weight: "600",
  body_font_size: "14px",
  body_font_weight: "300",
  input_bg_color: "#4B4B4B",
  input_border_radius: "0px",
  button_variant: "contained",
  button_border_radius: "0px",
  panel_border_radius: "0px",
  panel_box_shadow: "0px 8px 24px rgba(0, 0, 0, 0.16)",
  authn_show_name: "no",
  authn_show_social_icons: false,
  login_heading: "Sign in",
  login_button_label: "Sign in",
  login_social_heading: "Other ways to sign in",
  signup_heading: "Create your account",
  signup_button_label: "Create account",
  signup_social_heading: "Other ways to sign up",
  otp_button_label: "Submit",
};
